config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'base#index'
  # get 'search' => 'base#search'
  # post 'refresh_locations' => 'base#refresh_locations'
  get 'privacy' => 'base#privacy'

  get 'location' => 'base#location'
  get 'selection' => 'base#selection'
  get 'results' => 'base#results'

  post 'set_locale' => 'base#set_locale'

  # line bot
  post 'callback' => 'line#callback'
  # facebook bot
  get 'webhook' => 'facebook#webhook'
  post 'webhook' => 'facebook#post_webhook'
  # telegram bot
  # post 'update' => 'telegram#update'

  resources :users, only: %i[show edit update]
end

app/views/common/_ga_trace.html.slim
- if on_production?
	javascript:
	  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

	  ga('create', 'UA-96751882-2', 'auto');
	  ga('send', 'pageview');

app/views/common/_loading.html.slim
#loading.loader style="display: none"
  .ajax-spinner-bars
	.bar-1
	.bar-2
	.bar-3
	.bar-4
	.bar-5
	.bar-6
	.bar-7
	.bar-8
	.bar-9
	.bar-10
	.bar-11
	.bar-12
	.bar-13
	.bar-14
	.bar-15
	.bar-16

app/views/common/_map_script.html.slim
script[async defer src="https://maps.googleapis.com/maps/api/js?key=#{ENV['google_js_api_key']}&language=#{I18n.locale}&libraries=places&callback=initMap"]

app/views/common/_navbar.html.slim
nav.navbar.navbar-inverse.navbar-fixed-top.nav-custom
  .container
    .navbar-header
      = link_to " FoodSearch", location_url, data: { turbolinks: false }, class: "navbar-brand web-title", style: "margin: 3px 0 0 3px;"
      = button_tag t('locale'), id: 'locale-button', class: "navbar-toggle btn-custom", data: { target: ".navbar-collapse", toggle: "collapse"}
    div.collapse.navbar-collapse
      ul.nav.navbar-nav.navbar-right
        li class="#{'active' if I18n.locale == :"zh-TW"}"
          = link_to '中文', '', id: 'zh-tw-locale'
        / li class="#{'active' if I18n.locale == :ja}"
        /   = link_to '日本語', '', id: 'ja-locale'
        / li class="#{'active' if I18n.locale == :ko}"
        /   = link_to '한국어', '', id: 'ko-locale'
        li class="#{'active' if I18n.locale == :en}"
          = link_to 'English', '', id: 'en-locale'
      / - if current_page?(root_path)
      /   a.navbar-brand href=search_path
      /     i.fa.fa-search
      / - if current_page?(search_path)
      /   a.navbar-brand.search-icon#search-link href=""
      /     i.fa.fa-search.fa-2x.search_icon_size
      /   a.navbar-brand.map-icon#map-link href=""
      /     i.fa.fa-map-marker.fa-2x

javascript:
  rails_env = "#{Rails.env}"

app/views/common/_select.html.slim
- selected_sort = cookies['mode'].present? ? cookies['mode'] : ''
- selected_display = cookies['display'].present? ? cookies['display'] : ''
- selected_type = cookies['type'].present? ? cookies['type'] : ''

.select
  / = i18n_label(:type_mode)
  = select_tag('type-mode', options_for_select([[i18n_label(:restaurant), 'restaurant'], [i18n_label(:coffee), 'coffee']], selected: selected_type), class: 'form-control')
  / = i18n_label(:display_mode)
  = select_tag('display-mode', options_for_select([[i18n_label(:wrap), 'wrap'], [i18n_label(:nowrap), 'nowrap']], selected: selected_display), class: 'form-control')
  / = i18n_label(:search_mode)
  = select_tag('sort-mode', options_for_select([[i18n_label(:score), 'score'], [i18n_label(:distance), 'distance']], selected: selected_sort), class: 'form-control')